param(
    [string]$Workspace = "third_party/netsurf-workspace",
    [string]$BuildDir = "build/netsurf",
    [string]$Output = "build/user/nshtmltest.elf"
)

$ErrorActionPreference = "Stop"
$required = @("libparserutils", "libwapcaplet", "libhubbub", "libdom",
              "libcss", "libnsutils")
foreach ($name in $required) {
    if (!(Test-Path -LiteralPath (Join-Path $Workspace $name))) {
        throw "Missing $name. Run tools/fetch-netsurf.ps1 first."
    }
}

& python tools/gen-netsurf-aliases.py (Join-Path $Workspace "libparserutils")
if ($LASTEXITCODE -ne 0) { throw "Could not generate charset aliases" }
& python tools/gen-netsurf-entities.py (Join-Path $Workspace "libhubbub")
if ($LASTEXITCODE -ne 0) { throw "Could not generate HTML entities" }
& python tools/gen-netsurf-elements.py (Join-Path $Workspace "libhubbub")
if ($LASTEXITCODE -ne 0) { throw "Could not generate HTML element lookup" }

New-Item -ItemType Directory -Force $BuildDir | Out-Null
$generator = Join-Path $BuildDir "gen_parser.exe"
$generatorSource = Join-Path $Workspace "libcss/src/parse/properties/css_property_parser_gen.c"
$zig = Get-Command zig.exe -ErrorAction SilentlyContinue
if ($null -ne $zig) {
    # The generator is a host utility, not a freestanding BuzzOS binary.
    # Prefer Zig's bundled Windows libc when the machine has no MSVC SDK;
    # this keeps the otherwise freestanding build independent of host headers.
    & $zig.Source cc $generatorSource -D_CRT_SECURE_NO_WARNINGS -o $generator
} else {
    & clang $generatorSource -D_CRT_SECURE_NO_WARNINGS -o $generator
}
if ($LASTEXITCODE -ne 0) { throw "Could not build CSS property generator" }
$propertyRoot = Join-Path $Workspace "libcss/src/parse/properties"
foreach ($line in Get-Content (Join-Path $propertyRoot "properties.gen")) {
    if ($line -match '^([^#][^:]+):') {
        $name = $Matches[1].Trim()
        & $generator -o (Join-Path $propertyRoot "autogenerated_$name.c") $line
        if ($LASTEXITCODE -ne 0) { throw "Could not generate CSS property $name" }
    }
}

$common = @(
    "--target=x86_64-none-elf", "-std=c11", "-ffreestanding", "-fno-builtin",
    "-fno-stack-protector", "-fno-pic", "-mcmodel=large", "-mno-red-zone",
    "-mno-stack-arg-probe", "-O2",
    "-DNDEBUG", "-DWITHOUT_ICONV_FILTER", "-D__serenity__",
    "-D_ALIGNED=__attribute__((aligned))", "-DSTMTEXPR=1",
    "-Isrc/user/libc"
)
$pu = Join-Path $Workspace "libparserutils"
$wc = Join-Path $Workspace "libwapcaplet"
$hb = Join-Path $Workspace "libhubbub"
$dom = Join-Path $Workspace "libdom"
$css = Join-Path $Workspace "libcss"
$nsutils = Join-Path $Workspace "libnsutils"
$testIncludes = @(
    "-I$pu/include", "-I$pu/src", "-I$wc/include",
    "-I$hb/include", "-I$hb/src",
    "-I$dom/include", "-I$dom/src", "-I$dom/bindings/hubbub",
    "-I$css/include", "-I$css/src",
    "-I$nsutils/include", "-I$nsutils/src"
)
$compiledObjects = [Collections.Generic.List[string]]::new()

function Compile-Source([IO.FileInfo]$File, [string]$Root, [string]$Group) {
    $outDir = Join-Path $BuildDir $Group
    New-Item -ItemType Directory -Force $outDir | Out-Null
    $rootPath = (Resolve-Path $Root).Path
    $relative = $File.FullName.Substring($rootPath.Length + 1)
    $objectName = $relative.Replace("\", "_").Replace("/", "_").Replace(".c", ".o")
    $object = Join-Path $outDir $objectName
    $groupIncludes = @(switch ($Group) {
        "parserutils" { @("-I$pu/include", "-I$pu/src") }
        "wapcaplet" { @("-I$wc/include") }
        "hubbub" { @("-I$hb/include", "-I$hb/src", "-I$pu/include") }
        "dom" { @("-I$dom/include", "-I$dom/src", "-I$dom/bindings/hubbub",
                  "-I$pu/include", "-I$wc/include", "-I$hb/include") }
        "css" { @("-I$css/include", "-I$css/src", "-I$pu/include",
                  "-I$wc/include") }
        "nsutils" { @("-I$nsutils/include", "-I$nsutils/src") }
    })
    & clang @common @groupIncludes -c $File.FullName -o $object
    if ($LASTEXITCODE -ne 0) { throw "Compile failed: $($File.FullName)" }
    $compiledObjects.Add((Resolve-Path $object).Path)
}

Get-ChildItem (Join-Path $pu "src") -Recurse -Filter *.c |
    ForEach-Object { Compile-Source $_ (Join-Path $pu "src") "parserutils" }
Compile-Source (Get-Item (Join-Path $wc "src/libwapcaplet.c")) $wc "wapcaplet"
Get-ChildItem (Join-Path $hb "src") -Recurse -Filter *.c |
    Where-Object { $_.Name -ne "autogenerated-element-type.c" } |
    ForEach-Object { Compile-Source $_ (Join-Path $hb "src") "hubbub" }
Get-ChildItem (Join-Path $dom "src") -Recurse -Filter *.c |
    ForEach-Object { Compile-Source $_ $dom "dom" }
Compile-Source (Get-Item (Join-Path $dom "bindings/hubbub/parser.c")) $dom "dom"
Get-ChildItem (Join-Path $css "src") -Recurse -Filter *.c |
    Where-Object { $_.Name -ne "css_property_parser_gen.c" } |
    ForEach-Object { Compile-Source $_ (Join-Path $css "src") "css" }
Get-ChildItem (Join-Path $nsutils "src") -Recurse -Filter *.c |
    ForEach-Object { Compile-Source $_ (Join-Path $nsutils "src") "nsutils" }

& clang @common @testIncludes -c src/user/bin/nshtmltest.c -o (Join-Path $BuildDir "nshtmltest.o")
if ($LASTEXITCODE -ne 0) { throw "Could not compile nshtmltest" }
$objects = @("build/user/crt0.o", "build/user/libc.o",
             (Join-Path $BuildDir "nshtmltest.o")) + @($compiledObjects)
$responseFile = Join-Path $BuildDir "link-nshtmltest.rsp"
$linkArguments = @("-m", "elf_x86_64", "-z", "max-page-size=0x1000",
                   "-T", "build/user/user.ld",
                   "-nostdlib", "-o", $Output) + $objects
$linkArguments | ForEach-Object { '"' + $_ + '"' } |
    Set-Content -Encoding Ascii $responseFile
& ld.lld "@$responseFile"
if ($LASTEXITCODE -ne 0) { throw "Could not link nshtmltest" }
& llvm-objcopy --strip-sections $Output
if ($LASTEXITCODE -ne 0) { throw "Could not strip nshtmltest" }
Write-Host "Built $Output ($((Get-Item $Output).Length) bytes)"
