#!/usr/bin/env python3
"""Generate C arrays for NetSurf's built-in CSS resources."""

from pathlib import Path
import argparse


def emit_array(name: str, data: bytes) -> str:
    values = list(data) + [0]
    rows = []
    for offset in range(0, len(values), 16):
        rows.append("    " + ", ".join(f"0x{value:02x}" for value in values[offset:offset + 16]))
    return (
        f"static const uint8_t {name}[] = {{\n" + ",\n".join(rows) + "\n};\n"
        f"static const size_t {name}_size = sizeof({name}) - 1;\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--netsurf", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()
    root = Path(args.netsurf)
    resources = {
        "buzzos_default_css": root / "resources" / "default.css",
        "buzzos_adblock_css": root / "resources" / "adblock.css",
        "buzzos_internal_css": root / "resources" / "internal.css",
        "buzzos_quirks_css": root / "resources" / "quirks.css",
    }
    output = [
        "/* Generated by tools/embed-netsurf-resources.py. */\n",
        "#ifndef BUZZOS_NETSURF_RESOURCES_H\n#define BUZZOS_NETSURF_RESOURCES_H\n",
        "#include <stddef.h>\n#include <stdint.h>\n",
        "static const uint8_t buzzos_empty_css[] = { 0 };\n",
    ]
    for name, path in resources.items():
        output.append(emit_array(name, path.read_bytes()))
    output.append("#endif\n")
    destination = Path(args.output)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text("".join(output), encoding="ascii", newline="\n")


if __name__ == "__main__":
    main()
