#!/usr/bin/env python3
import pathlib
import sys


def main() -> int:
    root = pathlib.Path(sys.argv[1])
    source = root / "src" / "treebuilder" / "element-type.gperf"
    entries = []
    in_table = False
    for raw in source.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if line == "%%":
            in_table = not in_table
            continue
        if not in_table or not line:
            continue
        name, value = (part.strip() for part in line.split(",", 1))
        entries.append((name, value))

    lines = [
        "/* Generated from element-type.gperf for the BuzzOS port. */",
        "#include <string.h>",
        "#include <strings.h>",
        "",
        "static const struct element_type_map wordlist[] = {",
    ]
    lines += [f'\t{{ "{name}", {value} }},' for name, value in entries]
    lines += [
        "};",
        "",
        "static const struct element_type_map *",
        "hubbub_element_type_generated_lookup(const char *name, size_t length)",
        "{",
        "\tfor (size_t i = 0; i < sizeof(wordlist) / sizeof(wordlist[0]); i++) {",
        "\t\tif (strlen(wordlist[i].name) == length &&",
        "\t\t    strncasecmp(wordlist[i].name, name, length) == 0)",
        "\t\t\treturn &wordlist[i];",
        "\t}",
        "\treturn NULL;",
        "}",
        "",
    ]
    target = root / "src" / "treebuilder" / "autogenerated-element-type.c"
    target.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
