#!/usr/bin/env python3
import argparse
import contextlib
import io
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def fail(message):
    raise SystemExit(f"gen_app_registry: {message}")


def read_text(path):
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        fail(f"missing {path.relative_to(ROOT)}")


def c_ident(name):
    out = []
    for ch in name:
        out.append(ch if ch.isalnum() else "_")
    return "".join(out)


def c_string_literal(text):
    out = ['"']
    # A C narrow string stores UTF-8 bytes, not Unicode code points.
    for code in text.encode("utf-8"):
        if code == 10:
            out.append(r"\n")
        elif code == 9:
            out.append(r"\t")
        elif code == 34:
            out.append(r"\"")
        elif code == 92:
            out.append(r"\\")
        elif 32 <= code <= 126:
            out.append(chr(code))
        else:
            out.append(f"\\{code:03o}")
    out.append('"')
    return "".join(out)


def emit_c_string(symbol, text):
    print(f"static const char {symbol}[] =")
    lines = text.splitlines(keepends=True)
    if not lines:
        lines = [""]
    for i, line in enumerate(lines):
        suffix = ";" if i == len(lines) - 1 else ""
        print(f"    {c_string_literal(line)}{suffix}")
    print("")


def parse_manifest(text):
    result = {}
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            fail(f"bad manifest line: {raw}")
        key, value = line.split("=", 1)
        result[key.strip()] = value.strip()
    return result


def manifest_required(app, manifest):
    required = ["name", "kind", "version", "summary", "exec", "state", "source"]
    missing = [key for key in required if not manifest.get(key)]
    if missing:
        fail(f"{app}.app missing keys: {', '.join(missing)}")
    expected_exec = f"/fs/apps/{app}"
    if manifest["exec"] != expected_exec:
        fail(f"{app}.app exec must be {expected_exec}")
    source = ROOT / manifest["source"]
    if not source.exists():
        fail(f"{app}.app source does not exist: {manifest['source']}")


def app_macro(name):
    return c_ident(name).upper()


def generate(apps, seeds):
    print("// Auto-generated by tools/gen_app_registry.py; do not edit by hand.")
    print("#ifndef BUZZOS_APP_REGISTRY_H")
    print("#define BUZZOS_APP_REGISTRY_H")
    print("")
    print("#include <stddef.h>")
    print("")
    print("struct app_seed_entry {")
    print("    const char *path;")
    print("    const void *data;")
    print("    size_t size;")
    print("    int refresh;")
    print("};")
    print("")

    entries = []
    for app in apps:
        ident = c_ident(app)
        manifest_path = ROOT / "src" / "user" / "bin" / f"{app}.app"
        readme_path = ROOT / "src" / "user" / "bin" / f"{app}.readme"
        seed_path = ROOT / "src" / "user" / "bin" / f"{app}.seed"

        manifest_text = read_text(manifest_path)
        readme_text = read_text(readme_path)
        manifest = parse_manifest(manifest_text)
        manifest_required(app, manifest)
        readme_target = manifest.get("readme", f"/fs/apps/{app}.readme")

        emit_c_string(f"app_{ident}_manifest", manifest_text)
        emit_c_string(f"app_{ident}_readme", readme_text)
        entries.append((manifest["exec"], f"initrd_bin_{ident}_data", f"INITRD_BIN_{app_macro(app)}_SIZE", 1))
        entries.append((f"/fs/apps/{app}.app", f"app_{ident}_manifest", f"sizeof(app_{ident}_manifest) - 1", 1))
        entries.append((readme_target, f"app_{ident}_readme", f"sizeof(app_{ident}_readme) - 1", 0))

        if seed_path.exists():
            seed_text = read_text(seed_path)
            emit_c_string(f"app_{ident}_seed", seed_text)
            entries.append((manifest["state"], f"app_{ident}_seed", f"sizeof(app_{ident}_seed) - 1", 0))

    for target, source in seeds:
        seed_text = read_text(source)
        symbol = f"file_seed_{c_ident(target.strip('/'))}"
        emit_c_string(symbol, seed_text)
        entries.append((target, symbol, f"sizeof({symbol}) - 1", 0))

    print("static const struct app_seed_entry app_seed_entries[] = {")
    for path, data, size, refresh in entries:
        print(f"    {{ {c_string_literal(path)}, {data}, {size}, {refresh} }},")
    print("};")
    print(f"static const size_t app_seed_entry_count = {len(entries)};")
    print("")
    print("#endif /* BUZZOS_APP_REGISTRY_H */")


def main():
    parser = argparse.ArgumentParser(description="Generate kernel app seeding registry")
    parser.add_argument("--apps", required=True, help="space-separated GUI_APP_NAMES value")
    parser.add_argument(
        "--seed",
        action="append",
        default=[],
        metavar="/fs/PATH=SOURCE",
        help="seed an ordinary UTF-8 file through the same persistent-file registry",
    )
    parser.add_argument("--out", help="write UTF-8 output to this path instead of stdout")
    args = parser.parse_args()
    apps = args.apps.split()
    seeds = []
    for spec in args.seed:
        if "=" not in spec:
            fail(f"bad --seed value: {spec}")
        target, source_text = spec.split("=", 1)
        if not target.startswith("/fs/") or target.endswith("/"):
            fail(f"seed target must be a file below /fs: {target}")
        source = ROOT / source_text
        seeds.append((target, source))
    if args.out:
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            generate(apps, seeds)
        out = ROOT / args.out if not Path(args.out).is_absolute() else Path(args.out)
        out.write_text(buf.getvalue(), encoding="utf-8", newline="\n")
    else:
        generate(apps, seeds)


if __name__ == "__main__":
    main()
