param(
    [string]$Out = "src/user/libc/font_ui.h",
    [string]$FontFile = "C:/Windows/Fonts/segoeui.ttf",
    [int]$FontSize = 24,
    [int]$CellWidth = 32,
    [int]$CellHeight = 36,
    [string]$Symbol = "uifont",
    [string]$Macro = "UIFONT"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Drawing
if (!(Test-Path -LiteralPath $FontFile)) { throw "UI font not found: $FontFile" }
$collection = [Drawing.Text.PrivateFontCollection]::new()
$collection.AddFontFile($FontFile)
$font = [Drawing.Font]::new($collection.Families[0], $FontSize, [Drawing.FontStyle]::Regular, [Drawing.GraphicsUnit]::Pixel)
$format = [Drawing.StringFormat]::GenericTypographic.Clone()
$format.FormatFlags = $format.FormatFlags -bor [Drawing.StringFormatFlags]::MeasureTrailingSpaces
$lines = [Collections.Generic.List[string]]::new()
$advances = [Collections.Generic.List[string]]::new()
$lines.Add("/* Generated by tools/gen_ui_font.ps1: local UI face, ${FontSize}px. */")
$lines.Add("#ifndef BUZZOS_${Macro}_H")
$lines.Add("#define BUZZOS_${Macro}_H")
$lines.Add("#include <stdint.h>")
$lines.Add("enum { ${Macro}_FIRST = 32, ${Macro}_COUNT = 95, ${Macro}_WIDTH = $CellWidth, ${Macro}_HEIGHT = $CellHeight };")
$lines.Add("static const uint8_t ${Symbol}_alpha[${Macro}_COUNT][${Macro}_HEIGHT][${Macro}_WIDTH] = {")
try {
    for ($code = 32; $code -le 126; $code++) {
        $bitmap = [Drawing.Bitmap]::new($CellWidth, $CellHeight, [Drawing.Imaging.PixelFormat]::Format32bppArgb)
        $graphics = [Drawing.Graphics]::FromImage($bitmap)
        try {
            $graphics.Clear([Drawing.Color]::Black)
            $graphics.TextRenderingHint = [Drawing.Text.TextRenderingHint]::AntiAliasGridFit
            $graphics.PixelOffsetMode = [Drawing.Drawing2D.PixelOffsetMode]::Half
            $character = [string][char]$code
            $advance = [Math]::Ceiling($graphics.MeasureString($character, $font, [Drawing.PointF]::Empty, $format).Width)
            if ($advance -lt 1 -or $advance -ge $CellWidth) { throw "Invalid advance for $code" }
            $advances.Add([string][int]$advance)
            $graphics.DrawString($character, $font, [Drawing.Brushes]::White, [single]0, [single]0, $format)
            $lines.Add("    /* $code */ {")
            for ($y = 0; $y -lt $CellHeight; $y++) {
                $row = [Collections.Generic.List[string]]::new()
                for ($x = 0; $x -lt $CellWidth; $x++) {
                    $pixel = $bitmap.GetPixel($x, $y)
                    $row.Add([string][int][Math]::Round(($pixel.R + $pixel.G + $pixel.B) / 3.0))
                }
                $lines.Add("        {" + [string]::Join(",", $row) + "},")
            }
            $lines.Add("    },")
        } finally { $graphics.Dispose(); $bitmap.Dispose() }
    }
    $lines.Add("};")
    $lines.Add("static const uint8_t ${Symbol}_advance[${Macro}_COUNT] = {" + [string]::Join(",", $advances) + "};")
    $lines.Add("#endif")
    $outPath = [IO.Path]::GetFullPath($Out)
    [IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($outPath)) | Out-Null
    [IO.File]::WriteAllLines($outPath, $lines, [Text.Encoding]::ASCII)
    Write-Host "Generated proportional UI font: $outPath"
} finally { $format.Dispose(); $font.Dispose(); $collection.Dispose() }
