param(
    [string]$Out = "src/kernel/drv/font_unicode_data.h",
    [string]$FontFile = "",
    [int]$CellHeight = 22,
    [int]$NarrowWidth = 12,
    [int]$WideWidth = 24,
    [int]$FontSize = 18,
    [int]$OffsetX = 0,
    [int]$OffsetY = -2
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Drawing

if ($FontFile -eq "") {
    $candidates = @(
        "C:\Windows\Fonts\NotoSansSC-VF.ttf",
        "C:\Windows\Fonts\Deng.ttf",
        "C:\Windows\Fonts\simhei.ttf"
    )
    foreach ($candidate in $candidates) {
        if (Test-Path $candidate) { $FontFile = $candidate; break }
    }
}
if ($FontFile -eq "" -or !(Test-Path $FontFile)) {
    throw "No Unicode CJK font found (tried Noto Sans SC, DengXian, SimHei)"
}

$set = New-Object 'System.Collections.Generic.HashSet[int]'
function Add-Range([int]$First, [int]$Last) {
    for ($cp = $First; $cp -le $Last; $cp++) { [void]$set.Add($cp) }
}
Add-Range 0x00A0 0x024F  # Latin supplement and extended
Add-Range 0x0370 0x052F  # Greek and Cyrillic
Add-Range 0x2000 0x206F  # General punctuation
Add-Range 0x3000 0x30FF  # CJK punctuation, Hiragana, Katakana
Add-Range 0xFF00 0xFFEF  # Full-width forms

# GB2312 gives a compact, deterministic set of roughly 7,500 common Chinese
# characters without embedding all 20,992 unified ideographs.
$gb = [System.Text.Encoding]::GetEncoding(936)
for ($lead = 0xA1; $lead -le 0xF7; $lead++) {
    for ($trail = 0xA1; $trail -le 0xFE; $trail++) {
        $text = $gb.GetString([byte[]]@($lead, $trail))
        if ($text.Length -gt 0 -and $text[0] -ne [char]0xFFFD) {
            $cp = [char]::ConvertToUtf32($text, 0)
            if ($cp -gt 0x7F) { [void]$set.Add($cp) }
        }
    }
}
$points = [int[]]$set
[Array]::Sort($points)

$outPath = [IO.Path]::GetFullPath($Out)
[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($outPath)) | Out-Null
$pfc = New-Object Drawing.Text.PrivateFontCollection
$pfc.AddFontFile($FontFile)
$font = New-Object Drawing.Font($pfc.Families[0], [single]$FontSize,
    [Drawing.FontStyle]::Regular, [Drawing.GraphicsUnit]::Pixel)
$bmp = New-Object Drawing.Bitmap($WideWidth, $CellHeight,
    [Drawing.Imaging.PixelFormat]::Format32bppArgb)
$graphics = [Drawing.Graphics]::FromImage($bmp)
$graphics.TextRenderingHint = [Drawing.Text.TextRenderingHint]::SingleBitPerPixelGridFit
$graphics.PixelOffsetMode = [Drawing.Drawing2D.PixelOffsetMode]::Half
$brush = [Drawing.Brushes]::White
$format = [Drawing.StringFormat]::GenericTypographic.Clone()
$format.FormatFlags = $format.FormatFlags -bor [Drawing.StringFormatFlags]::MeasureTrailingSpaces
$strideBytes = [int][Math]::Floor(($WideWidth + 7) / 8)
$glyphBytes = $strideBytes * $CellHeight

function Is-Wide([int]$Cp) {
    return ($Cp -ge 0x2E80 -and $Cp -le 0x9FFF) -or
           ($Cp -ge 0x3000 -and $Cp -le 0x30FF) -or
           ($Cp -ge 0xFF00 -and $Cp -le 0xFFEF)
}

$sb = New-Object Text.StringBuilder
[void]$sb.AppendLine("/* Generated by tools/gen_unicode_font.ps1. Do not edit. */")
[void]$sb.AppendLine("#ifndef BUZZOS_FONT_UNICODE_DATA_H")
[void]$sb.AppendLine("#define BUZZOS_FONT_UNICODE_DATA_H")
[void]$sb.AppendLine("#include <stdint.h>")
[void]$sb.AppendLine("enum { KFONT_UNICODE_COUNT = $($points.Length), KFONT_UNICODE_STRIDE = $strideBytes, KFONT_UNICODE_BYTES = $glyphBytes };")
[void]$sb.AppendLine("static const uint32_t kfont_unicode_codepoints[KFONT_UNICODE_COUNT] = {")
for ($i = 0; $i -lt $points.Length; $i += 12) {
    [void]$sb.Append("    ")
    for ($j = $i; $j -lt [Math]::Min($i + 12, $points.Length); $j++) {
        [void]$sb.Append(("0x{0:X}u," -f $points[$j]))
    }
    [void]$sb.AppendLine()
}
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("static const uint8_t kfont_unicode_widths[KFONT_UNICODE_COUNT] = {")
for ($i = 0; $i -lt $points.Length; $i += 32) {
    [void]$sb.Append("    ")
    for ($j = $i; $j -lt [Math]::Min($i + 32, $points.Length); $j++) {
        [void]$sb.Append($(if (Is-Wide $points[$j]) { "$WideWidth," } else { "$NarrowWidth," }))
    }
    [void]$sb.AppendLine()
}
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("static const uint8_t kfont_unicode_bits[KFONT_UNICODE_COUNT][KFONT_UNICODE_BYTES] = {")

$rect = New-Object Drawing.Rectangle(0, 0, $WideWidth, $CellHeight)
for ($index = 0; $index -lt $points.Length; $index++) {
    $graphics.Clear([Drawing.Color]::Black)
    $glyph = [char]::ConvertFromUtf32($points[$index])
    $graphics.DrawString($glyph, $font, $brush, [single]$OffsetX, [single]$OffsetY, $format)
    $data = $bmp.LockBits($rect, [Drawing.Imaging.ImageLockMode]::ReadOnly,
        [Drawing.Imaging.PixelFormat]::Format32bppArgb)
    $bitmapStride = $data.Stride
    $raw = New-Object byte[] ($bitmapStride * $CellHeight)
    [Runtime.InteropServices.Marshal]::Copy($data.Scan0, $raw, 0, $raw.Length)
    $bmp.UnlockBits($data)
    $packed = New-Object byte[] $glyphBytes
    for ($y = 0; $y -lt $CellHeight; $y++) {
        for ($x = 0; $x -lt $WideWidth; $x++) {
            $off = $y * $bitmapStride + $x * 4
            if (($raw[$off] + $raw[$off + 1] + $raw[$off + 2]) -ge 72) {
                $poff = $y * $strideBytes + [int][Math]::Floor($x / 8)
                $packed[$poff] = $packed[$poff] -bor (0x80 -shr ($x % 8))
            }
        }
    }
    [void]$sb.Append("    {")
    for ($i = 0; $i -lt $packed.Length; $i++) {
        [void]$sb.Append(("0x{0:X2}," -f $packed[$i]))
    }
    [void]$sb.AppendLine("},")
    if (($index % 500) -eq 0) {
        Write-Progress -Activity "Generating Unicode font" -Status "$index / $($points.Length)" -PercentComplete (100 * $index / $points.Length)
    }
}
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("#endif")
[IO.File]::WriteAllText($outPath, $sb.ToString(), [Text.Encoding]::ASCII)
$format.Dispose(); $graphics.Dispose(); $bmp.Dispose(); $font.Dispose(); $pfc.Dispose()
Write-Host "Generated $outPath with $($points.Length) Unicode glyphs from $FontFile"
