import re
import sys
import hashlib

BYTES_PER_LINE = 32


def ident(path):
    name = path.strip("/")
    if not name:
        name = "root"
    name = re.sub(r"[^A-Za-z0-9_]", "_", name)
    return "initrd_" + name


def emit(name, file_path, seen):
    with open(file_path, "rb") as f:
        data = f.read()

    var = ident(name)
    digest = hashlib.sha256(data).digest()
    existing = seen.get(digest)
    if existing is not None:
        print(f"#define {var.upper()}_SIZE {existing.upper()}_SIZE")
        print(f"#define {var}_data {existing}_data")
        print("")
        return
    seen[digest] = var
    print(f"#define {var.upper()}_SIZE {len(data)}")
    print(f'static const uint8_t {var}_data[{var.upper()}_SIZE] __attribute__((used)) = {{')
    for i in range(0, len(data), BYTES_PER_LINE):
        line = ", ".join(f"0x{b:02X}" for b in data[i:i + BYTES_PER_LINE])
        print(f"    {line},")
    print("};")
    print("")


print("// Auto-generated by tools/mkinitrd.py")
seen_payloads = {}

if len(sys.argv) == 2:
    emit("init", sys.argv[1], seen_payloads)
elif len(sys.argv) > 2 and len(sys.argv[1:]) % 2 == 0:
    args = sys.argv[1:]
    for i in range(0, len(args), 2):
        emit(args[i], args[i + 1], seen_payloads)
else:
    raise SystemExit("usage: mkinitrd.py <elf> OR mkinitrd.py <path> <elf> ...")
